### ISSUE TITLE
Can't understand how to install Pyrate in Freecad

### ISSUE THREAD

**Issue by giacomomarchioro** [mess42/pyrate#91]
Dear mess42, 
I can't understand how to install Pyrate workbench in FreeCAD 16.0 on Ubuntu 16.04.

This is what I have done:

```
sudo apt-get install python python-numpy python-scipy python-matplotlib python-yaml python-sympy
cd ~/.FreeCAD/Mod
git clone https://github.com/mess42/pyrate.git
cd pyrate
sudo python setup.py install 
```

Opening FreeCAD there is no workbench. 

Thanks, 
Best regards, 
Giacomo

**Comment by looooo** [comment]
I just tried to install with pip and there are some problems:
- `init_gui.py` should be inside of workbench
- you need to import everything from `freecad.PyrateWorkbench`
- use relative import or change to `from freecad.PyrateWorkbench import ...`

If you want I can try to resolve this. But I guess you are still supporting the old way to install FreeCAD packages.

**Comment by joha2** [comment]
@looooo in fact the FreeCAD functionality is completely broken since our last refactor. Therefore I would appreciat if you would fix those things, but I think the functionality of the FreeCAD interface is still broken. Could you please explain which changes you want to do?

Best wishes
Johannes

**Comment by looooo** [comment]
have a look here:
like I said you should move everything into the `pyrate/freecad/PyrateWorkbench` directory. There should only be a __init__.py in the `pyrate/freecad` directory.

And you also must change the imports to be
- relative: `from .subpackage.module import my_class`
- or absolute: `from freecad.PyrateWorkbench.subpackage.module import my_class`

the current style works only with python2 (bad relative import) or the old FreeCAD module structure.

**Comment by joha2** [comment]
I think porting to python3 is planned anyways if FreeCAD is also ported to python3. Is there a possibility to prepare the imports in such a manner that they could be also used in python3 later without rewriting everything?

**Comment by looooo** [comment]
yes simple do it in the way I proposed. ; )
In python2 you can import relative in two ways.
`from . import module`
`import module`
In python3 only the first works.

**Comment by joha2** [comment]
Yeah thanks for the hint. But first of all the main point for the FreeCAD interface is to create an intermediate class structure by using dicts to make the data exchange possible.

**Comment by joha2** [comment]
@looooo I have added your changes to my source.

**Comment by luzpaz** [comment]
I'm tracking the progress of FreeCAD workbenches migration to py3/qt5
Should I use this issue or open a new one to track the progress of pyrate to py3 ?

**Comment by linuxcf** [comment]
I, too, cannot see the pyrate WB selection as of the latest pyrate update (10-JAN-2019).  Are the comments above still valid?  I am asking this because a couple of weeks ago I *could* see the pyrate WB option from the WB dropdown menu. Now I don't see the pyrate WB option and I get the following error messages in the report window of FreeCAD (I had to insert the asterisks at the end of the dashes because otherwise the font came out large and bold; I don't know why):

During initialization the error No module named ruamel.yaml occurred in freecad.PyrateWorkbench
--------------------------------------------------------------------------------*
Traceback (most recent call last):
  File "<string>", line 145, in InitApplications
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/lcf/.FreeCAD/Mod/pyrate/freecad/PyrateWorkbench/init_gui.py", line 65, in <module>
    from freecad.PyrateWorkbench import Commands_OpticalSystem
  File "/home/lcf/.FreeCAD/Mod/pyrate/freecad/PyrateWorkbench/Commands_OpticalSystem.py", line 33, in <module>
    from .Observer_OpticalSystem import OpticalSystemObserver
  File "/home/lcf/.FreeCAD/Mod/pyrate/freecad/PyrateWorkbench/Observer_OpticalSystem.py", line 33, in <module>
    from pyrateoptics.material import material_isotropic
  File "/home/lcf/.FreeCAD/Mod/pyrate/pyrateoptics/__init__.py", line 41, in <module>
    from .raytracer.optical_system import OpticalSystem
  File "/home/lcf/.FreeCAD/Mod/pyrate/pyrateoptics/raytracer/optical_system.py", line 29, in <module>
    from ..material.material_isotropic import ConstantIndexGlass
  File "/home/lcf/.FreeCAD/Mod/pyrate/pyrateoptics/material/material_isotropic.py", line 29, in <module>
    from ..core.base import OptimizableVariable
  File "/home/lcf/.FreeCAD/Mod/pyrate/pyrateoptics/core/base.py", line 29, in <module>
    import ruamel.yaml as yaml
ImportError: No module named ruamel.yaml
--------------------------------------------------------------------------------*

**Comment by joha2** [comment]
@linuxcf thanks for reporting this bug. First of all: It seems that the yaml library ruamel.yaml is not available to the Python interpreter in FreeCAD or in your system wide Python installation. Maybe you should first get it via "sudo pip install ruamel.yaml". Best wishes
Johannes

**Comment by joha2** [comment]
There is a thread in the FreeCAD forum:

https://forum.freecadweb.org/viewtopic.php?p=274044

About another "WB does not appear" after start up. Maybe it also helps you to fix your problem besides the missing ruamel.yaml module.
